// ============================================================
// PLUs OFICIALES del PDF "CARNICERIAS FABRICIUS - CODIGOS PLU - BALANZA"
// ============================================================
// Lista canónica de los 106 PLU configurados en la balanza Cuora Max.
// Cada entry: { plu, nombre, seccion }
//
// Las secciones siguen exactamente el agrupamiento del PDF físico.
// Mantener sincronizado con `supabase/14_seed_productos_plu.sql`.
// ============================================================

export const PLUS_OFICIALES = [
  // BOVINO - CORTES (1-34)
  { plu: 1,  nombre: 'CUADRIL-NALGA-PECETO', seccion: 'BOVINO - CORTES' },
  { plu: 2,  nombre: 'JAMON CUADRADO-BOLA DE LOMO-PULPA PALETA', seccion: 'BOVINO - CORTES' },
  { plu: 3,  nombre: 'COSTILLA', seccion: 'BOVINO - CORTES' },
  { plu: 4,  nombre: 'VACIO', seccion: 'BOVINO - CORTES' },
  { plu: 5,  nombre: 'PICANA/TAPA DE CUADRIL', seccion: 'BOVINO - CORTES' },
  { plu: 6,  nombre: 'CORTE AMERICANO-ENTRECOT', seccion: 'BOVINO - CORTES' },
  { plu: 7,  nombre: 'COLITA CUADRIL', seccion: 'BOVINO - CORTES' },
  { plu: 8,  nombre: 'TAPA DE NALGA', seccion: 'BOVINO - CORTES' },
  { plu: 9,  nombre: 'TAPA DE ASADO', seccion: 'BOVINO - CORTES' },
  { plu: 10, nombre: 'COSTELETA/CARRE', seccion: 'BOVINO - CORTES' },
  { plu: 11, nombre: 'AGUJA ESPECIAL', seccion: 'BOVINO - CORTES' },
  { plu: 12, nombre: 'AGUJA ECONOMICA', seccion: 'BOVINO - CORTES' },
  { plu: 13, nombre: 'BOCADO FINO', seccion: 'BOVINO - CORTES' },
  { plu: 14, nombre: 'BOCADO ANCHO', seccion: 'BOVINO - CORTES' },
  { plu: 15, nombre: 'LOMITO', seccion: 'BOVINO - CORTES' },
  { plu: 16, nombre: 'MOLIDA SEMIESPECIAL', seccion: 'BOVINO - CORTES' },
  { plu: 17, nombre: 'MOLIDA ESPECIAL', seccion: 'BOVINO - CORTES' },
  { plu: 18, nombre: 'FALDA ESPECIAL', seccion: 'BOVINO - CORTES' },
  { plu: 19, nombre: 'FALDA ECONOMICA', seccion: 'BOVINO - CORTES' },
  { plu: 20, nombre: 'FALDA DESHUESADA', seccion: 'BOVINO - CORTES' },
  { plu: 21, nombre: 'MILANESA COMUN', seccion: 'BOVINO - CORTES' },
  { plu: 22, nombre: 'MILANESA DE PECETO', seccion: 'BOVINO - CORTES' },
  { plu: 23, nombre: 'MILANESA DE NALGA', seccion: 'BOVINO - CORTES' },
  { plu: 24, nombre: 'OSOBUCO', seccion: 'BOVINO - CORTES' },
  { plu: 25, nombre: 'PUCHERO ECONOMICO', seccion: 'BOVINO - CORTES' },
  { plu: 26, nombre: 'TORTUGA-CARNAZA', seccion: 'BOVINO - CORTES' },
  { plu: 27, nombre: 'ALBONDIGA', seccion: 'BOVINO - CORTES' },
  { plu: 28, nombre: 'HAMBURGUESA', seccion: 'BOVINO - CORTES' },
  { plu: 29, nombre: 'HAMBURGUESA RELLENA C/MUZZARELLA', seccion: 'BOVINO - CORTES' },
  { plu: 30, nombre: 'MATAMBRE', seccion: 'BOVINO - CORTES' },
  { plu: 31, nombre: 'BIFE DE CHORIZO Y OJO DE BIFE', seccion: 'BOVINO - CORTES' },
  { plu: 32, nombre: 'CHIQUIZUELA', seccion: 'BOVINO - CORTES' },
  { plu: 33, nombre: 'ROAST BEEF', seccion: 'BOVINO - CORTES' },
  { plu: 34, nombre: 'BOCADO DESHUESADO', seccion: 'BOVINO - CORTES' },
  // BOVINO - PIEZAS (35-44)
  { plu: 35, nombre: 'PIERNA', seccion: 'BOVINO - PIEZAS' },
  { plu: 36, nombre: 'COSTILLAR COMPLETO', seccion: 'BOVINO - PIEZAS' },
  { plu: 37, nombre: 'COSTILLAR CON VACIO', seccion: 'BOVINO - PIEZAS' },
  { plu: 38, nombre: 'COSTILLAR', seccion: 'BOVINO - PIEZAS' },
  { plu: 39, nombre: 'PARRILLERO', seccion: 'BOVINO - PIEZAS' },
  { plu: 40, nombre: 'CORTITO', seccion: 'BOVINO - PIEZAS' },
  { plu: 41, nombre: 'MEDIA RES C/DESPOSTE EMBOLSADO', seccion: 'BOVINO - PIEZAS' },
  { plu: 42, nombre: 'MEDIA RES DESPOSTADA EN PIEZAS', seccion: 'BOVINO - PIEZAS' },
  { plu: 43, nombre: 'CUARTO PISTOLA', seccion: 'BOVINO - PIEZAS' },
  { plu: 44, nombre: 'PALETA', seccion: 'BOVINO - PIEZAS' },
  // ACHURAS (45-53)
  { plu: 45, nombre: 'ENTRANA DE COSTILLAR', seccion: 'ACHURAS' },
  { plu: 46, nombre: 'CHINCHULIN-RINON', seccion: 'ACHURAS' },
  { plu: 47, nombre: 'MOLLEJA SURTIDA', seccion: 'ACHURAS' },
  { plu: 48, nombre: 'MONDONGO', seccion: 'ACHURAS' },
  { plu: 49, nombre: 'SESOS (LA UNIDAD)', seccion: 'ACHURAS' },
  { plu: 50, nombre: 'LENGUA', seccion: 'ACHURAS' },
  { plu: 51, nombre: 'CORAZON-TRIPA GORDA', seccion: 'ACHURAS' },
  { plu: 52, nombre: 'HIGADO', seccion: 'ACHURAS' },
  { plu: 53, nombre: 'RABO', seccion: 'ACHURAS' },
  // CERDO (54-73)
  { plu: 54, nombre: 'BONDIOLA', seccion: 'CERDO' },
  { plu: 55, nombre: 'MATAMBRE CERDO', seccion: 'CERDO' },
  { plu: 56, nombre: 'PULPA CERDO', seccion: 'CERDO' },
  { plu: 57, nombre: 'COSTELETA CERDO', seccion: 'CERDO' },
  { plu: 58, nombre: 'CORTE AMERICANO/ENTRECOT CERDO', seccion: 'CERDO' },
  { plu: 59, nombre: 'COSTILLA CERDO', seccion: 'CERDO' },
  { plu: 60, nombre: 'VACIO CERDO', seccion: 'CERDO' },
  { plu: 61, nombre: 'LOMO CERDO', seccion: 'CERDO' },
  { plu: 62, nombre: 'HAMBURGUESAS CERDO', seccion: 'CERDO' },
  { plu: 63, nombre: 'CHORIZO', seccion: 'CERDO' },
  { plu: 64, nombre: 'CHORIZO SABORIZADO', seccion: 'CERDO' },
  { plu: 65, nombre: 'CHORIZO COLORADO', seccion: 'CERDO' },
  { plu: 66, nombre: 'CHORIZO CUNE', seccion: 'CERDO' },
  { plu: 67, nombre: 'MORCILLA', seccion: 'CERDO' },
  { plu: 68, nombre: 'CUERITO', seccion: 'CERDO' },
  { plu: 69, nombre: 'HUESITOS/PATITAS', seccion: 'CERDO' },
  { plu: 70, nombre: 'BOCADO CERDO', seccion: 'CERDO' },
  { plu: 71, nombre: 'OSOBUCO CERDO', seccion: 'CERDO' },
  { plu: 72, nombre: 'SALCHICHA PARRILLERA', seccion: 'CERDO' },
  { plu: 73, nombre: 'MILANESA CERDO', seccion: 'CERDO' },
  // CERDO - PIEZAS (74-77)
  { plu: 74, nombre: 'PECHITO', seccion: 'CERDO - PIEZAS' },
  { plu: 75, nombre: 'PIERNA CERDO', seccion: 'CERDO - PIEZAS' },
  { plu: 76, nombre: 'PALETA DE CERDO', seccion: 'CERDO - PIEZAS' },
  { plu: 77, nombre: 'CARRE', seccion: 'CERDO - PIEZAS' },
  // EMBUTIDOS (78-86)
  { plu: 78, nombre: 'SALAME CASERO ENV.', seccion: 'EMBUTIDOS' },
  { plu: 79, nombre: 'SALAME CASERO SIN ENVASAR', seccion: 'EMBUTIDOS' },
  { plu: 80, nombre: 'PROVOLETA', seccion: 'EMBUTIDOS' },
  { plu: 81, nombre: 'BONDIOLA EMBUTIDO', seccion: 'EMBUTIDOS' },
  { plu: 82, nombre: 'LOMO EMBUTIDO', seccion: 'EMBUTIDOS' },
  { plu: 83, nombre: 'PANCETA', seccion: 'EMBUTIDOS' },
  { plu: 84, nombre: 'QUESO CERDO ENV.', seccion: 'EMBUTIDOS' },
  { plu: 85, nombre: 'ARROLLADO DE CERDO', seccion: 'EMBUTIDOS' },
  { plu: 86, nombre: 'JAMON CRUDO', seccion: 'EMBUTIDOS' },
  // POLLO (87-94)
  { plu: 87, nombre: 'PECHUGA', seccion: 'POLLO' },
  { plu: 88, nombre: 'POLLO FRESCO', seccion: 'POLLO' },
  { plu: 89, nombre: 'PATA MUSLO', seccion: 'POLLO' },
  { plu: 90, nombre: 'ALITA', seccion: 'POLLO' },
  { plu: 91, nombre: 'ARROLLADO DE POLLO', seccion: 'POLLO' },
  { plu: 92, nombre: 'MILANESA DE PECHUGA', seccion: 'POLLO' },
  { plu: 93, nombre: 'HAMBURGUESA POLLO', seccion: 'POLLO' },
  { plu: 94, nombre: 'HAMBURGUESA RELLENA C/MUZZARELLA POLLO', seccion: 'POLLO' },
  // REBOZADOS (95-102)
  { plu: 95,  nombre: 'BOCADITOS/CANONCITOS MUZZARELLA GRANGYS', seccion: 'REBOZADOS' },
  { plu: 96,  nombre: 'NUGGETS INDACOR', seccion: 'REBOZADOS' },
  { plu: 97,  nombre: 'MEDALLON DE POLLO JYQ GRANGYS', seccion: 'REBOZADOS' },
  { plu: 98,  nombre: 'MEDALLON DE MERLUZA GRANGYS', seccion: 'REBOZADOS' },
  { plu: 99,  nombre: 'FILET DE MERLUZA', seccion: 'REBOZADOS' },
  { plu: 100, nombre: 'PAPAS BASTON CONGELADAS', seccion: 'REBOZADOS' },
  { plu: 101, nombre: 'PAPAS NOISETTE CONGELADAS', seccion: 'REBOZADOS' },
  { plu: 102, nombre: 'PAPAS CARITAS CONGELADAS', seccion: 'REBOZADOS' },
  // LINEA DORADA (103-106)
  { plu: 103, nombre: 'TOMAHAWK', seccion: 'LINEA DORADA' },
  { plu: 104, nombre: 'RIB EYE/OJO DE BIFE', seccion: 'LINEA DORADA' },
  { plu: 105, nombre: 'ASADO VENTANA', seccion: 'LINEA DORADA' },
  { plu: 106, nombre: 'T-BONE', seccion: 'LINEA DORADA' },
]
