-- ============================================================
-- 101 — EL ID DE UN EMPLEADO LO PONE LA BASE, NO EL NAVEGADOR
-- ============================================================
-- PROBLEMA
-- `empleados_sueldos.id` es integer NOT NULL SIN default: el id lo calculaba
-- la pantalla con `select max(id) → +1`. Eso funcionaba cuando había un solo
-- negocio, pero con RLS por sucursal se rompe:
--
--   Monte Cristo NO VE los empleados de la central (así debe ser) → el max que
--   lee es NULL → intenta insertar id = 1 → ese id ya existe en la central →
--   "duplicate key". La sucursal NO PUEDE dar de alta a su gente.
--
-- Y aunque lo viera, dos bocas cargando un empleado al mismo tiempo elegirían
-- el mismo número.
--
-- SOLUCIÓN
-- Que el id lo genere la base (IDENTITY). La secuencia arranca después del
-- último id usado, así los 7 empleados actuales y sus liquidaciones históricas
-- (`liquidaciones_sueldos.empleado_id`, `conceptos_sueldos.empleado_id`) no se
-- tocan. Cada boca inserta sin pisar a la otra.
--
-- Idempotente: si ya es identity, no hace nada.
-- ============================================================

DO $$
BEGIN
  -- ¿ya es columna de identidad? (a = always, d = by default)
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'public.empleados_sueldos'::regclass
      AND attname = 'id' AND attidentity IN ('a', 'd')
  ) THEN
    ALTER TABLE empleados_sueldos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- La secuencia tiene que empezar DESPUÉS del último id que ya existe, o el
-- primer alta chocaría con un empleado viejo.
SELECT setval(
  pg_get_serial_sequence('empleados_sueldos', 'id'),
  coalesce((SELECT max(id) FROM empleados_sueldos), 0) + 1,
  false
);

-- ============================================================
-- VERIFICACIÓN (correr aparte)
-- ============================================================
-- select column_default, is_identity from information_schema.columns
--  where table_name='empleados_sueldos' and column_name='id';   -- is_identity = YES
--
-- Alta desde la sucursal, sin mandar id (así queda la pantalla):
-- begin;
-- set local role authenticated;
-- set local request.jwt.claims = '{"sub":"76336959-024c-4ea8-83ab-135de8cdfd3a","role":"authenticated"}';
-- insert into empleados_sueldos (apellido, nombre, valor_hora) values ('PRUEBA','TEST',1000)
--   returning id, sucursal_id;   -- id nuevo (8+) y sucursal_id 3 puesto por el trigger
-- rollback;
-- ============================================================
