-- ============================================================
-- 156 — Delivery minorista (app de pedidos para el público)
-- ============================================================
-- El público pide desde /pedir SIN usuario: nunca toca las tablas
-- directo. Todo pasa por 4 funciones SECURITY DEFINER que validan
-- horario, mínimo, cantidades y recalculan los precios del lado del
-- servidor (el precio que manda el celular no se usa nunca).
--
-- Etapa 1 = solo Río Primero: sale de la central (Mitre 670), con la
-- lista MINORISTA de la central y sus ofertas. Mayoristas y carnicerías
-- no usan el delivery. Monte Cristo viene después (cada boca vende lo
-- suyo) — por eso la tabla ya lleva sucursal_id.
--
-- Circuito: nuevo → pesado (el local carga los kilos reales y avisa el
-- total por WhatsApp) → pagado (si es transferencia) → en_camino →
-- entregado. El cobro se registra en la Caja como una venta común
-- (descuenta stock y entra al arqueo); venta_id la linkea.
-- ============================================================

-- Productos que el local no quiere publicar en el delivery.
alter table public.precios add column if not exists delivery_oculto boolean not null default false;

create table if not exists public.pedidos_delivery (
  id              bigint generated by default as identity primary key,  -- es el N° de pedido que ve el cliente
  token           uuid not null unique default gen_random_uuid(),       -- link de seguimiento (secreto)
  sucursal_id     integer not null default 1,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  cliente_nombre  text not null,
  telefono        text not null,
  direccion       text not null,
  referencias     text,
  nota            text,
  forma_pago      text not null check (forma_pago in ('efectivo','transferencia')),
  -- [{producto_id, nombre, categoria, pesable, cantidad, precio, importe, nota, kg_real, importe_real}]
  items           jsonb not null,
  subtotal_aprox  numeric not null,
  envio           numeric not null default 0,
  total_aprox     numeric not null,
  subtotal_final  numeric,
  total_final     numeric,
  estado          text not null default 'nuevo'
                  check (estado in ('nuevo','pesado','pagado','en_camino','entregado','cancelado')),
  motivo_cancelacion text,
  pesado_at       timestamptz,
  transferencia_avisada_at timestamptz,   -- el cliente tocó "Ya transferí"
  pagado_at       timestamptz,
  en_camino_at    timestamptz,
  entregado_at    timestamptz,
  cancelado_at    timestamptz,
  venta_id        uuid references public.ventas_minoristas(id) on delete set null
);

create index if not exists pedidos_delivery_estado_idx on public.pedidos_delivery (sucursal_id, estado, created_at desc);
create index if not exists pedidos_delivery_tel_idx on public.pedidos_delivery (telefono, created_at desc);

alter table public.pedidos_delivery enable row level security;

drop policy if exists pedidos_delivery_admin on public.pedidos_delivery;
create policy pedidos_delivery_admin on public.pedidos_delivery
  for all using (is_admin()) with check (is_admin());

-- Cada boca ve sólo sus pedidos (hoy todos son de la central).
drop policy if exists pedidos_delivery_boca on public.pedidos_delivery;
create policy pedidos_delivery_boca on public.pedidos_delivery
  as restrictive for all
  using (sucursal_id = mi_sucursal()) with check (sucursal_id = mi_sucursal());

-- Realtime: el panel del local y el globito del menú se enteran al instante.
do $$ begin
  alter publication supabase_realtime add table public.pedidos_delivery;
exception when duplicate_object then null; end $$;

-- Configuración (editable desde el panel: pausar, envío, mínimo, alias…)
insert into public.config_sistema (clave, valor, descripcion)
values ('delivery', jsonb_build_object(
  'activo', true,
  'localidad', 'Río Primero',
  'sale_de', 'Mitre 670',
  'envio', 2000,
  'minimo', 20000,
  'alias', 'fabrilenardon.mp',
  'whatsapp', '',
  'categorias', jsonb_build_array('bovino_corte','bovino_brosa','cerdo_corte','pollo','embutido','rebozado'),
  'horarios', jsonb_build_array(
    jsonb_build_object('dias', jsonb_build_array(1,2,3,4,5,6), 'desde', '09:00', 'hasta', '12:00'),
    jsonb_build_object('dias', jsonb_build_array(1,2,3,4,5,6), 'desde', '17:30', 'hasta', '20:00')
  )
), 'Delivery minorista: horarios de toma de pedidos, envío, mínimo y alias (mig 156)')
on conflict (clave) do nothing;

-- ── ¿Se están tomando pedidos ahora? (hora ARGENTINA, no la del servidor) ──
create or replace function public.delivery_esta_abierto(cfg jsonb)
returns boolean language sql stable set search_path = public as $$
  select coalesce((cfg->>'activo')::boolean, false) and exists (
    select 1
    from jsonb_array_elements(coalesce(cfg->'horarios', '[]'::jsonb)) h
    where extract(isodow from (now() at time zone 'America/Argentina/Buenos_Aires'))::int
            in (select jsonb_array_elements_text(h->'dias')::int)
      and (now() at time zone 'America/Argentina/Buenos_Aires')::time >= (h->>'desde')::time
      and (now() at time zone 'America/Argentina/Buenos_Aires')::time <  (h->>'hasta')::time
  )
$$;

-- ── Los productos publicados, con el precio minorista y la oferta vigente ──
-- Misma regla que la Caja (resolverPrecio): oferta activa de la central,
-- dentro de fechas, que aplique a la lista minorista; descuento_pct pisa a
-- precio_oferta. Los que se venden por pieza entera quedan afuera (en la
-- Caja abren un selector de pieza individual).
create or replace function public.delivery_productos()
returns table (id uuid, nombre text, categoria text, pesable boolean,
               precio numeric, precio_base numeric, oferta boolean)
language sql stable security definer set search_path = public as $$
  with cfg as (select valor from config_sistema where clave = 'delivery'),
  hoy as (select (now() at time zone 'America/Argentina/Buenos_Aires')::date d)
  select p.id, trim(p.nombre), p.categoria, coalesce(p.pesable, true),
         coalesce(o.precio, p.precio_minorista) as precio,
         p.precio_minorista as precio_base,
         o.precio is not null and o.precio < p.precio_minorista as oferta
  from precios p
  cross join cfg
  left join lateral (
    select case
             when coalesce(ofe.descuento_pct, 0) > 0 then round(p.precio_minorista * (1 - ofe.descuento_pct / 100))
             when coalesce(ofe.precio_oferta, 0) > 0 then ofe.precio_oferta
           end as precio
    from ofertas ofe, hoy
    where ofe.precio_id = p.id
      and ofe.activa
      and ofe.aplica_minorista is not false
      and coalesce(ofe.sucursal_id, 1) = 1
      and ofe.fecha_inicio <= hoy.d and ofe.fecha_fin >= hoy.d
    order by ofe.created_at desc
    limit 1
  ) o on true
  where p.sucursal_id is null
    and p.precio_minorista > 0
    and not p.delivery_oculto
    and coalesce(p.vende_por_pieza, false) = false
    and p.categoria in (select jsonb_array_elements_text(cfg.valor->'categorias'))
$$;

-- ── Catálogo público ──
create or replace function public.delivery_catalogo()
returns jsonb language sql stable security definer set search_path = public as $$
  with cfg as (select valor from config_sistema where clave = 'delivery')
  select jsonb_build_object(
    'config', (select valor - 'categorias' from cfg),
    'abierto', (select delivery_esta_abierto(valor) from cfg),
    'productos', coalesce((select jsonb_agg(to_jsonb(dp) order by dp.categoria, dp.nombre) from delivery_productos() dp), '[]'::jsonb)
  )
$$;

-- ── Crear un pedido ──
create or replace function public.delivery_crear_pedido(p jsonb)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  cfg jsonb;
  v_nombre text := btrim(coalesce(p->>'nombre', ''));
  v_tel text := regexp_replace(coalesce(p->>'telefono', ''), '\D', '', 'g');
  v_dir text := btrim(coalesce(p->>'direccion', ''));
  v_ref text := nullif(btrim(coalesce(p->>'referencias', '')), '');
  v_nota text := nullif(btrim(coalesce(p->>'nota', '')), '');
  v_pago text := coalesce(p->>'forma_pago', '');
  v_items jsonb := '[]'::jsonb;
  v_subtotal numeric := 0;
  v_envio numeric;
  v_minimo numeric;
  it jsonb;
  prod record;
  v_cant numeric;
  v_importe numeric;
  v_id bigint;
  v_token uuid;
begin
  select valor into cfg from config_sistema where clave = 'delivery';
  if cfg is null or not delivery_esta_abierto(cfg) then
    raise exception 'CERRADO' using hint = 'Ahora no se están tomando pedidos.';
  end if;
  if length(v_nombre) < 2 or length(v_nombre) > 80 then raise exception 'NOMBRE'; end if;
  if length(v_tel) < 8 or length(v_tel) > 15 then raise exception 'TELEFONO'; end if;
  if length(v_dir) < 4 or length(v_dir) > 200 then raise exception 'DIRECCION'; end if;
  if v_pago not in ('efectivo', 'transferencia') then raise exception 'PAGO'; end if;
  if jsonb_typeof(p->'items') <> 'array' or jsonb_array_length(p->'items') < 1
     or jsonb_array_length(p->'items') > 40 then
    raise exception 'ITEMS';
  end if;

  -- Freno al abuso: el link es público.
  if (select count(*) from pedidos_delivery
      where telefono = v_tel and estado in ('nuevo','pesado','pagado','en_camino')) >= 3 then
    raise exception 'DEMASIADOS';
  end if;
  if (select count(*) from pedidos_delivery where created_at > now() - interval '1 hour') >= 60 then
    raise exception 'SATURADO';
  end if;

  for it in select * from jsonb_array_elements(p->'items') loop
    select * into prod from delivery_productos() dp where dp.id::text = it->>'producto_id';
    if not found then raise exception 'PRODUCTO'; end if;
    v_cant := (it->>'cantidad')::numeric;
    if prod.pesable then
      if v_cant is null or v_cant < 0.1 or v_cant > 20 then raise exception 'CANTIDAD'; end if;
      v_cant := round(v_cant, 3);
    else
      if v_cant is null or v_cant < 1 or v_cant > 50 or v_cant <> trunc(v_cant) then raise exception 'CANTIDAD'; end if;
    end if;
    v_importe := round(v_cant * prod.precio);
    v_subtotal := v_subtotal + v_importe;
    v_items := v_items || jsonb_build_object(
      'producto_id', prod.id, 'nombre', prod.nombre, 'categoria', prod.categoria,
      'pesable', prod.pesable, 'cantidad', v_cant, 'precio', prod.precio,
      'oferta', prod.oferta, 'importe', v_importe,
      'nota', nullif(left(btrim(coalesce(it->>'nota', '')), 200), ''));
  end loop;

  v_envio := coalesce((cfg->>'envio')::numeric, 0);
  v_minimo := coalesce((cfg->>'minimo')::numeric, 0);
  if v_subtotal < v_minimo then raise exception 'MINIMO'; end if;

  insert into pedidos_delivery (sucursal_id, cliente_nombre, telefono, direccion, referencias, nota,
                                forma_pago, items, subtotal_aprox, envio, total_aprox)
  values (1, v_nombre, v_tel, v_dir, left(v_ref, 200), left(v_nota, 300),
          v_pago, v_items, v_subtotal, v_envio, v_subtotal + v_envio)
  returning id, token into v_id, v_token;

  return jsonb_build_object('numero', v_id, 'token', v_token);
end $$;

-- ── Seguimiento (sólo con el token del link) ──
create or replace function public.delivery_ver_pedido(p_token uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'numero', d.id, 'estado', d.estado, 'created_at', d.created_at,
    'cliente_nombre', d.cliente_nombre, 'direccion', d.direccion, 'forma_pago', d.forma_pago,
    'items', d.items, 'subtotal_aprox', d.subtotal_aprox, 'envio', d.envio, 'total_aprox', d.total_aprox,
    'subtotal_final', d.subtotal_final, 'total_final', d.total_final,
    'motivo_cancelacion', d.motivo_cancelacion,
    'pesado_at', d.pesado_at, 'transferencia_avisada_at', d.transferencia_avisada_at,
    'pagado_at', d.pagado_at, 'en_camino_at', d.en_camino_at,
    'entregado_at', d.entregado_at, 'cancelado_at', d.cancelado_at,
    'alias', c.valor->>'alias', 'whatsapp', c.valor->>'whatsapp'
  )
  from pedidos_delivery d
  left join config_sistema c on c.clave = 'delivery'
  where d.token = p_token
$$;

-- ── El cliente avisa que ya transfirió ──
create or replace function public.delivery_avisar_transferencia(p_token uuid)
returns boolean language sql volatile security definer set search_path = public as $$
  update pedidos_delivery
     set transferencia_avisada_at = now(), updated_at = now()
   where token = p_token and forma_pago = 'transferencia' and estado = 'pesado'
     and transferencia_avisada_at is null
  returning true
$$;

revoke all on function public.delivery_productos() from public;
revoke all on function public.delivery_catalogo() from public;
revoke all on function public.delivery_crear_pedido(jsonb) from public;
revoke all on function public.delivery_ver_pedido(uuid) from public;
revoke all on function public.delivery_avisar_transferencia(uuid) from public;
grant execute on function public.delivery_catalogo() to anon, authenticated;
grant execute on function public.delivery_crear_pedido(jsonb) to anon, authenticated;
grant execute on function public.delivery_ver_pedido(uuid) to anon, authenticated;
grant execute on function public.delivery_avisar_transferencia(uuid) to anon, authenticated;
grant execute on function public.delivery_productos() to authenticated;
