-- ============================================================
-- 157 — Delivery: cuentas de cliente con clave + cupón automático
-- ============================================================
-- El cliente del delivery se registra con nombre y apellido, teléfono,
-- dirección y una CLAVE DE 4 NÚMEROS (PIN). Pedido de Fabricio: sin
-- clave cualquiera podría pedir a nombre de otro, ver su historial o
-- usarle el cupón.
--
-- Estas cuentas NO son usuarios del sistema (auth.users/profiles): viven
-- en su propia tabla y se manejan sólo por funciones SECURITY DEFINER.
-- Así un cliente del delivery nunca puede llegar a ver nada del sistema.
--
-- Sesión = un token (uuid) que la app guarda en el celular. 5 claves mal
-- seguidas bloquean la cuenta 15 minutos. Si se olvida la clave, el
-- local se la resetea desde el panel (delivery_resetear_pin).
--
-- Cupón: cada `cupon_cada` pedidos ENTREGADOS, el siguiente lleva
-- `cupon_pct` % de descuento en la carne (el envío se cobra igual). Se
-- asigna al crear el pedido; si ese pedido se cancela, el cupón vuelve.
-- ============================================================

create table if not exists public.clientes_delivery (
  id                bigint generated by default as identity primary key,
  telefono          text not null unique,          -- sólo dígitos: es el "usuario"
  nombre            text not null,
  direccion         text not null,
  referencias       text,
  pin_hash          text not null,
  intentos_fallidos integer not null default 0,
  bloqueado_hasta   timestamptz,
  notas             text,                           -- notas internas del local
  created_at        timestamptz not null default now(),
  ultimo_ingreso    timestamptz
);

create table if not exists public.sesiones_delivery (
  token       uuid primary key default gen_random_uuid(),
  cliente_id  bigint not null references public.clientes_delivery(id) on delete cascade,
  created_at  timestamptz not null default now(),
  ultimo_uso  timestamptz not null default now()
);
create index if not exists sesiones_delivery_cliente_idx on public.sesiones_delivery (cliente_id);

alter table public.pedidos_delivery add column if not exists cliente_id bigint references public.clientes_delivery(id) on delete set null;
alter table public.pedidos_delivery add column if not exists cupon boolean not null default false;
alter table public.pedidos_delivery add column if not exists descuento_pct numeric;
alter table public.pedidos_delivery add column if not exists descuento_monto numeric;
create index if not exists pedidos_delivery_cliente_idx on public.pedidos_delivery (cliente_id, created_at desc);

-- Clientes: el local los ve (para la ficha y el historial). El público
-- nunca entra directo: sólo por las funciones de abajo.
alter table public.clientes_delivery enable row level security;
drop policy if exists clientes_delivery_admin on public.clientes_delivery;
create policy clientes_delivery_admin on public.clientes_delivery
  for all using (is_admin() and es_central()) with check (is_admin() and es_central());

-- Sesiones: sin policies a propósito (nadie las lee directo; ni el admin).
alter table public.sesiones_delivery enable row level security;

-- El hash nunca sale de la base, ni para el panel. Un REVOKE de columna no
-- alcanza si el rol tiene SELECT de toda la tabla (Supabase lo da por
-- defecto): se saca el de tabla y se dan las columnas una por una.
revoke all on public.clientes_delivery from anon, authenticated;
grant select (id, telefono, nombre, direccion, referencias, intentos_fallidos, bloqueado_hasta, notas, created_at, ultimo_ingreso)
  on public.clientes_delivery to authenticated;
grant update (nombre, direccion, referencias, notas) on public.clientes_delivery to authenticated;
revoke all on public.sesiones_delivery from anon, authenticated;

update public.config_sistema
   set valor = valor || jsonb_build_object('cupon_cada', coalesce(valor->'cupon_cada', '5'::jsonb),
                                           'cupon_pct',  coalesce(valor->'cupon_pct', '10'::jsonb))
 where clave = 'delivery';

-- ── Helpers internos ──
create or replace function public.delivery_cliente_de_token(p_token uuid)
returns bigint language sql volatile security definer set search_path = public as $$
  update sesiones_delivery set ultimo_uso = now()
   where token = p_token and ultimo_uso > now() - interval '180 days'
  returning cliente_id
$$;

-- Cuántos pedidos entregó y si tiene un cupón para usar.
create or replace function public.delivery_estado_cupon(p_cliente bigint)
returns jsonb language sql stable security definer set search_path = public as $$
  with cfg as (
    select greatest(coalesce((valor->>'cupon_cada')::int, 0), 0) cada,
           coalesce((valor->>'cupon_pct')::numeric, 0) pct
    from config_sistema where clave = 'delivery'
  ),
  n as (
    select count(*) filter (where estado = 'entregado') entregados,
           count(*) filter (where cupon and estado <> 'cancelado') usados
    from pedidos_delivery where cliente_id = p_cliente
  )
  select jsonb_build_object(
    'cada', cfg.cada, 'pct', cfg.pct, 'entregados', n.entregados,
    'disponible', cfg.cada > 0 and cfg.pct > 0 and (n.entregados / cfg.cada) > n.usados,
    -- pedidos entregados que le faltan para el próximo cupón
    'faltan', case when cfg.cada > 0 then cfg.cada - (n.entregados % cfg.cada) else null end
  )
  from cfg, n
$$;

create or replace function public.delivery_datos_cliente(p_cliente bigint)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object('id', c.id, 'nombre', c.nombre, 'telefono', c.telefono,
                            'direccion', c.direccion, 'referencias', c.referencias,
                            'cupon', delivery_estado_cupon(c.id))
  from clientes_delivery c where c.id = p_cliente
$$;

-- ── Registro ──
create or replace function public.delivery_registrar(p jsonb)
returns jsonb language plpgsql volatile security definer set search_path = public, extensions as $$
declare
  v_nombre text := btrim(coalesce(p->>'nombre', ''));
  v_tel text := regexp_replace(coalesce(p->>'telefono', ''), '\D', '', 'g');
  v_dir text := btrim(coalesce(p->>'direccion', ''));
  v_ref text := nullif(btrim(coalesce(p->>'referencias', '')), '');
  v_pin text := coalesce(p->>'pin', '');
  v_id bigint;
  v_token uuid;
begin
  if length(v_nombre) < 3 or length(v_nombre) > 80 then raise exception 'NOMBRE'; end if;
  if length(v_tel) < 8 or length(v_tel) > 15 then raise exception 'TELEFONO'; end if;
  if length(v_dir) < 4 or length(v_dir) > 200 then raise exception 'DIRECCION'; end if;
  if v_pin !~ '^\d{4}$' then raise exception 'PIN'; end if;
  if exists (select 1 from clientes_delivery where telefono = v_tel) then raise exception 'YA_EXISTE'; end if;
  if (select count(*) from clientes_delivery where created_at > now() - interval '1 hour') >= 40 then
    raise exception 'SATURADO';
  end if;

  insert into clientes_delivery (telefono, nombre, direccion, referencias, pin_hash, ultimo_ingreso)
  values (v_tel, v_nombre, v_dir, left(v_ref, 200), crypt(v_pin, gen_salt('bf')), now())
  returning id into v_id;
  insert into sesiones_delivery (cliente_id) values (v_id) returning token into v_token;
  return jsonb_build_object('token', v_token, 'cliente', delivery_datos_cliente(v_id));
end $$;

-- ── Ingreso con teléfono + clave ──
create or replace function public.delivery_ingresar(p_telefono text, p_pin text)
returns jsonb language plpgsql volatile security definer set search_path = public, extensions as $$
declare
  v_tel text := regexp_replace(coalesce(p_telefono, ''), '\D', '', 'g');
  c record;
  v_token uuid;
begin
  -- Los errores de ingreso VUELVEN como {"error": ...} en vez de RAISE: un
  -- RAISE deshace la llamada entera, contador de intentos incluido, y el
  -- bloqueo a los 5 intentos no se activaba nunca (visto al probarlo).
  select * into c from clientes_delivery where telefono = v_tel;
  if not found then return jsonb_build_object('error', 'NO_EXISTE'); end if;
  if c.bloqueado_hasta is not null and c.bloqueado_hasta > now() then
    return jsonb_build_object('error', 'BLOQUEADO');
  end if;
  if c.pin_hash <> crypt(coalesce(p_pin, ''), c.pin_hash) then
    update clientes_delivery
       set intentos_fallidos = case when intentos_fallidos + 1 >= 5 then 0 else intentos_fallidos + 1 end,
           bloqueado_hasta  = case when intentos_fallidos + 1 >= 5 then now() + interval '15 minutes' else bloqueado_hasta end
     where id = c.id;
    return jsonb_build_object('error', 'CLAVE');
  end if;
  update clientes_delivery set intentos_fallidos = 0, bloqueado_hasta = null, ultimo_ingreso = now() where id = c.id;
  insert into sesiones_delivery (cliente_id) values (c.id) returning token into v_token;
  return jsonb_build_object('token', v_token, 'cliente', delivery_datos_cliente(c.id));
end $$;

create or replace function public.delivery_salir(p_token uuid)
returns void language sql volatile security definer set search_path = public as $$
  delete from sesiones_delivery where token = p_token
$$;

-- ── Mi cuenta: datos, cupón e historial ──
create or replace function public.delivery_mi_cuenta(p_token uuid)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare v_cli bigint;
begin
  v_cli := delivery_cliente_de_token(p_token);
  if v_cli is null then raise exception 'SESION'; end if;
  return delivery_datos_cliente(v_cli) || jsonb_build_object('pedidos', coalesce((
    select jsonb_agg(jsonb_build_object(
             'numero', d.id, 'token', d.token, 'estado', d.estado, 'created_at', d.created_at,
             'total', coalesce(d.total_final, d.total_aprox), 'final', d.total_final is not null,
             'cupon', d.cupon, 'items', d.items) order by d.created_at desc)
    from (select * from pedidos_delivery where cliente_id = v_cli order by created_at desc limit 30) d
  ), '[]'::jsonb));
end $$;

create or replace function public.delivery_actualizar_datos(p_token uuid, p jsonb)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  v_cli bigint;
  v_nombre text := btrim(coalesce(p->>'nombre', ''));
  v_dir text := btrim(coalesce(p->>'direccion', ''));
begin
  v_cli := delivery_cliente_de_token(p_token);
  if v_cli is null then raise exception 'SESION'; end if;
  if length(v_nombre) < 3 or length(v_nombre) > 80 then raise exception 'NOMBRE'; end if;
  if length(v_dir) < 4 or length(v_dir) > 200 then raise exception 'DIRECCION'; end if;
  update clientes_delivery
     set nombre = v_nombre, direccion = v_dir,
         referencias = left(nullif(btrim(coalesce(p->>'referencias', '')), ''), 200)
   where id = v_cli;
  return delivery_datos_cliente(v_cli);
end $$;

-- ── El local le resetea la clave a un cliente (se la olvidó) ──
create or replace function public.delivery_resetear_pin(p_cliente bigint, p_pin text)
returns void language plpgsql volatile security definer set search_path = public, extensions as $$
begin
  if not (is_admin() and es_central()) then raise exception 'PERMISO'; end if;
  if coalesce(p_pin, '') !~ '^\d{4}$' then raise exception 'PIN'; end if;
  update clientes_delivery
     set pin_hash = crypt(p_pin, gen_salt('bf')), intentos_fallidos = 0, bloqueado_hasta = null
   where id = p_cliente;
  delete from sesiones_delivery where cliente_id = p_cliente;   -- cierra las sesiones abiertas
end $$;

-- ── Crear pedido: ahora con cuenta (token) y cupón ──
drop function if exists public.delivery_crear_pedido(jsonb);
create or replace function public.delivery_crear_pedido(p jsonb)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare
  cfg jsonb;
  v_cli bigint;
  cli record;
  v_dir text := btrim(coalesce(p->>'direccion', ''));
  v_ref text := nullif(btrim(coalesce(p->>'referencias', '')), '');
  v_nota text := nullif(btrim(coalesce(p->>'nota', '')), '');
  v_pago text := coalesce(p->>'forma_pago', '');
  v_items jsonb := '[]'::jsonb;
  v_subtotal numeric := 0;
  v_envio numeric;
  v_minimo numeric;
  v_cupon jsonb;
  v_pct numeric;
  v_desc numeric := 0;
  it jsonb;
  prod record;
  v_cant numeric;
  v_importe numeric;
  v_id bigint;
  v_token uuid;
begin
  select valor into cfg from config_sistema where clave = 'delivery';
  if cfg is null or not delivery_esta_abierto(cfg) then
    raise exception 'CERRADO' using hint = 'Ahora no se están tomando pedidos.';
  end if;
  begin
    v_cli := delivery_cliente_de_token((p->>'token')::uuid);
  exception when others then v_cli := null;
  end;
  if v_cli is null then raise exception 'SESION'; end if;
  select * into cli from clientes_delivery where id = v_cli;
  if v_dir = '' then v_dir := cli.direccion; v_ref := coalesce(v_ref, cli.referencias); end if;
  if length(v_dir) < 4 or length(v_dir) > 200 then raise exception 'DIRECCION'; end if;
  if v_pago not in ('efectivo', 'transferencia') then raise exception 'PAGO'; end if;
  if jsonb_typeof(p->'items') <> 'array' or jsonb_array_length(p->'items') < 1
     or jsonb_array_length(p->'items') > 40 then
    raise exception 'ITEMS';
  end if;

  if (select count(*) from pedidos_delivery
      where cliente_id = v_cli and estado in ('nuevo','pesado','pagado','en_camino')) >= 3 then
    raise exception 'DEMASIADOS';
  end if;
  if (select count(*) from pedidos_delivery where created_at > now() - interval '1 hour') >= 60 then
    raise exception 'SATURADO';
  end if;

  for it in select * from jsonb_array_elements(p->'items') loop
    select * into prod from delivery_productos() dp where dp.id::text = it->>'producto_id';
    if not found then raise exception 'PRODUCTO'; end if;
    v_cant := (it->>'cantidad')::numeric;
    if prod.pesable then
      if v_cant is null or v_cant < 0.1 or v_cant > 20 then raise exception 'CANTIDAD'; end if;
      v_cant := round(v_cant, 3);
    else
      if v_cant is null or v_cant < 1 or v_cant > 50 or v_cant <> trunc(v_cant) then raise exception 'CANTIDAD'; end if;
    end if;
    v_importe := round(v_cant * prod.precio);
    v_subtotal := v_subtotal + v_importe;
    v_items := v_items || jsonb_build_object(
      'producto_id', prod.id, 'nombre', prod.nombre, 'categoria', prod.categoria,
      'pesable', prod.pesable, 'cantidad', v_cant, 'precio', prod.precio,
      'oferta', prod.oferta, 'importe', v_importe,
      'nota', nullif(left(btrim(coalesce(it->>'nota', '')), 200), ''));
  end loop;

  v_envio := coalesce((cfg->>'envio')::numeric, 0);
  v_minimo := coalesce((cfg->>'minimo')::numeric, 0);
  if v_subtotal < v_minimo then raise exception 'MINIMO'; end if;   -- el mínimo es antes del descuento

  v_cupon := delivery_estado_cupon(v_cli);
  if (v_cupon->>'disponible')::boolean then
    v_pct := (v_cupon->>'pct')::numeric;
    v_desc := round(v_subtotal * v_pct / 100);
  end if;

  insert into pedidos_delivery (sucursal_id, cliente_id, cliente_nombre, telefono, direccion, referencias, nota,
                                forma_pago, items, subtotal_aprox, envio, total_aprox,
                                cupon, descuento_pct, descuento_monto)
  values (1, v_cli, cli.nombre, cli.telefono, v_dir, left(v_ref, 200), left(v_nota, 300),
          v_pago, v_items, v_subtotal, v_envio, v_subtotal - v_desc + v_envio,
          v_pct is not null, v_pct, case when v_pct is not null then v_desc end)
  returning id, token into v_id, v_token;

  -- La dirección que usó queda como la de su cuenta.
  update clientes_delivery set direccion = v_dir, referencias = coalesce(left(v_ref, 200), referencias)
   where id = v_cli and direccion is distinct from v_dir;

  return jsonb_build_object('numero', v_id, 'token', v_token);
end $$;

-- Seguimiento: suma el descuento del cupón.
create or replace function public.delivery_ver_pedido(p_token uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'numero', d.id, 'estado', d.estado, 'created_at', d.created_at,
    'cliente_nombre', d.cliente_nombre, 'direccion', d.direccion, 'forma_pago', d.forma_pago,
    'items', d.items, 'subtotal_aprox', d.subtotal_aprox, 'envio', d.envio, 'total_aprox', d.total_aprox,
    'subtotal_final', d.subtotal_final, 'total_final', d.total_final,
    'cupon', d.cupon, 'descuento_pct', d.descuento_pct, 'descuento_monto', d.descuento_monto,
    'motivo_cancelacion', d.motivo_cancelacion,
    'pesado_at', d.pesado_at, 'transferencia_avisada_at', d.transferencia_avisada_at,
    'pagado_at', d.pagado_at, 'en_camino_at', d.en_camino_at,
    'entregado_at', d.entregado_at, 'cancelado_at', d.cancelado_at,
    'alias', c.valor->>'alias', 'whatsapp', c.valor->>'whatsapp'
  )
  from pedidos_delivery d
  left join config_sistema c on c.clave = 'delivery'
  where d.token = p_token
$$;

revoke all on function public.delivery_cliente_de_token(uuid) from public, anon, authenticated;
revoke all on function public.delivery_estado_cupon(bigint) from public, anon;
revoke all on function public.delivery_datos_cliente(bigint) from public, anon, authenticated;
revoke all on function public.delivery_registrar(jsonb) from public;
revoke all on function public.delivery_ingresar(text, text) from public;
revoke all on function public.delivery_salir(uuid) from public;
revoke all on function public.delivery_mi_cuenta(uuid) from public;
revoke all on function public.delivery_actualizar_datos(uuid, jsonb) from public;
revoke all on function public.delivery_resetear_pin(bigint, text) from public, anon;
revoke all on function public.delivery_crear_pedido(jsonb) from public;
revoke all on function public.delivery_ver_pedido(uuid) from public;
grant execute on function public.delivery_registrar(jsonb) to anon, authenticated;
grant execute on function public.delivery_ingresar(text, text) to anon, authenticated;
grant execute on function public.delivery_salir(uuid) to anon, authenticated;
grant execute on function public.delivery_mi_cuenta(uuid) to anon, authenticated;
grant execute on function public.delivery_actualizar_datos(uuid, jsonb) to anon, authenticated;
grant execute on function public.delivery_crear_pedido(jsonb) to anon, authenticated;
grant execute on function public.delivery_ver_pedido(uuid) to anon, authenticated;
grant execute on function public.delivery_resetear_pin(bigint, text) to authenticated;
grant execute on function public.delivery_estado_cupon(bigint) to authenticated;
